Revert "Using new version of Gulp"
This reverts commit d9e8ac0a5023c6f2a99e147908fb05f9c81c3dbe.

$ gulp
[08:47:13] Requiring external module @babel/register
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined